fans:
  - id: Fan1
    hwmon:
      platform: nct6791
      index: 1
    neverStop: true
    curve: case_curve
  - id: Fan2
    hwmon:
      platform: nct6791
      index: 2
    neverStop: true
    curve: case_curve
  - id: Fan3
    hwmon:
      platform: nct6791
      index: 3
    neverStop: true
    curve: case_curve
  - id: Fan4
    hwmon:
      platform: nct6791
      index: 4
    neverStop: true
    curve: case_curve

sensors:
  - id: cpu_package
    hwmon:
      platform: coretemp
      index: 1

curves:
  - id: case_curve
    linear:
      sensor: cpu_package
      steps:
        - 40: 76
        - 60: 128
        - 75: 255
