# image will be published to ghcr.io/<user>/<name>
name: kindling
# description will be included in the image's metadata
description: Customised blue-os/bazzite-nvidia taking suggetions from bluefin, bluefin-dx and other sources in time. Largely targeting my machine.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: script
    scripts:
       - 00-move-files.sh
       - 01-prereqs.sh

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ganto/lxc4/repo/fedora-%OS_VERSION%/ganto-lxc4-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/karmab/kcli/repo/fedora-%OS_VERSION%/karmab-kcli-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/ubuntu-fonts/repo/fedora-%OS_VERSION%/atim-ubuntu-fonts-fedora-%OS_VERSION%.repo
      - https://terra.fyralabs.com/terra.repo
      - https://repo.vivaldi.com/stable/vivaldi-fedora.repo
    optfix:
      - vivaldi-stable
    install:
      - adobe-source-code-pro-fonts
      - alacritty
      - aardvark-dns
      - argyllcms
      - argyllcms-data
      - argyllcms-doc
      - autoconf
      - automake
      - bash-color-prompt
      - bcache-tools
      - binutils
      - bison
      - byacc
      - cargo
      - cascadia-code-fonts
      - ccache
      - cmake
      - cockpit
      - cockpit-bridge
      - cockpit-machines
      - cockpit-ostree
      - cockpit-pcp
      - code
      - container-selinux
      - containerd.io
      - cscope
      - ctags
      - dbus-x11
      - diffstat
      - distrobuilder
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - doxygen
      - edk2-ovmf
      - elfutils
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - evtest
      - firewall-config
      - flex
      - gcc
      - gcc-c++
      - gdb
      - genisoimage
      - gettext
      - git
      - git-credential-libsecret
      - git-credential-oauth
      - glibc-devel
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - gum
      - hplip
      - ibm-plex-mono-fonts
      - ifuse
      - incus
      - incus-agent
      - indent
      - input-leap
      - iotop
      - jetbrains-mono-fonts-all
      - kcli
      - libgda
      - libgda-sqlite
      - libimobiledevice
      - libnotify
      - libratbag-ratbagd
      - libsecret
      - libsecret-devel
      - libtool
      - libvirt
      - libvirt-client
      - libvirt-client-qemu
      - libvirt-daemon-kvm
      - libvirt-daemon-lxc
      - libvirt-daemon-qemu
      - lm_sensors
      - ltrace
      - lxc
      - lxd
      - lxd-agent
      - make
      - micro
      - mozilla-fira-mono-fonts
      - nautilus-gsconnect
      - netavark
      - nodejs-npm
      - p7zip
      - p7zip-plugins
      - patch
      - patchutils
      - perf
      - pkgconf
      - podman-compose
      - podman-plugins
      - podman-tui
      - podmansh
      - powerline-fonts
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-kvm
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - rclone
      - restic
      - rust
      - samba
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - slirp4netns
      - solaar
      - strace
      - stress-ng
      - subversion
      - systemtap
      - tmux
      - ubuntu-family-fonts
      - usbmuxd
      - util-linux-user
      - valgrind
      - variety
      - virt-manager
      - virt-viewer
      - vivaldi-stable
      - wireguard-tools
      - wl-clipboard
      - xprop
      - yaru-theme
      - zsh

      # - micro
      # - starship
    remove:
      #- podman-docker

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - gnome-vrr # enables gnome-vrr for your image
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-name: flathub-user
      repo-title: "Flathub (User)"

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - UbuntuMono
        #- GoMono
        - Inconsolata
        - IosevkaTerm
        #- MesloLG
      google-fonts:

  - type: script
    scripts:
        - 96-fetch-quadlets.sh
        - 97-oh-my-zsh.sh
        - 98-workarounds.sh
        - 99-post.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
